services:
  nerpybot-migrations:
    build:
      context: .
      target: migrations

  nerpybot:
    build:
      context: .
      target: bot

  humanmusic:
    build:
      context: .
      target: bot
